name: BalenaCloud Push

on:
  [push]

jobs:
  balena-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
      - run: npm install balena-cli -g --production --unsafe-perm
      - run: balena login --token ${{secrets.BALENA_API_TOKEN}}
      - run: balena push ${{secrets.BALENA_APPLICATION_NAME}}